@namespace
class SpriteKind:
    eat = SpriteKind.create()

def on_on_overlap(sprite, otherSprite):
    music.play_melody("E A B D B C G C5 ", 325)
    music.play_melody("E A B D B C G C5 ", 325)
    music.play_melody("E A B D B C G C5 ", 325)
    game.over(True, effects.confetti)
sprites.on_overlap(SpriteKind.player, SpriteKind.eat, on_on_overlap)

game.show_long_text("Welcome challenger, you must obtain the cloud in order to win!",
    DialogLayout.CENTER)
tiles.set_current_tilemap(tilemap("""
    level1
"""))
Guy = sprites.create(img("""
        .....ffffffffff.....
            ....ffbbbbbbbbff....
            ....fbbbbbbbbbbf....
            ...ffbbbbbbbbbbff...
            ...fbbffbbbffbbbf...
            ...fbbbbbbbbbbbbf...
            ...fbbf1bbbf1bbbf...
            ...fbbbbbbbbbbbbf...
            ...fbbbbbbbbbbbbf...
            ...fbbbbbbbbbbbbf...
            ...fbbbbffbbbbbbf...
            ...fbbbbbbbbbbbbf...
            ...fbbbbbbbbbbbbf...
            ...fbbbbbbbbbbbbf...
            ...fbbfffbbbfffbf...
            ...fbff.fbbff.fff...
            ...fff..ffff...ff...
            ...ff....ff.....f...
            ....................
            ....................
    """),
    SpriteKind.player)
tiles.place_on_tile(Guy, tiles.get_tile_location(3, 1))
scene.camera_follow_sprite(Guy)
controller.move_sprite(Guy)
deez_nuts_xD = sprites.create(img("""
        .........bbbb...........
            .......bb1111bb.........
            ......bb111111bbbbb.....
            ......b1111111ddd11b....
            ......b11111111d1111b...
            ...bbbd11111111d1111b...
            ..b11111111111111111bb..
            .b11111111111111111d11b.
            .b111d11111111111111111b
            cdd1d111111111111111111c
            cdddd11111111111111111dc
            cddbd11111d11111dd111dc.
            .cbbdd111dddd11ddbdddcc.
            .ccbbdddddbdddddddbcc...
            ...cccdddbbbdddddcc.....
            ......ccccccccccc.......
    """),
    SpriteKind.eat)
tiles.place_on_tile(deez_nuts_xD, tiles.get_tile_location(11, 18))